version: "3"

services:
  fpm_build:
    build:
      context: .
      dockerfile: Dockerfile-php
    command: ["composer", "install", "--no-dev"]
    environment:
     - APP_ENV=prod
    volumes:
     - ./project/:/var/www/project
