version: "3"

volumes:
  composer_cache:

services:
  fpm_build:
    build: 
      context: .
      dockerfile: alpine-dockerfile
    command: ["composer", "install", "--no-dev"]
    environment:
     - APP_ENV=prod
    volumes:
      - ./project/:/var/www/project
      - composer_cache:/root/.composer/cache

