version: "3"

services:
  fpm_test:
    build:
      context: .
      dockerfile: Dockerfile-php
    networks:
     - devops
    volumes:
      - ./project/:/var/www/project
      - composer_cache:/root/.composer/cache

networks:
  devops:
