---

- name: remove container
  docker_container:
    name: "symfony_project_fpm"
    state: absent


- name: Create a data container
  docker_container:
    name: "symfony_project_fpm" 
    image: "localhost:5000/symfony_project_fpm:latest"
    published_ports:
      - 8080:80
