---

#- name: remove container
#  docker_container:
#    name: "symfony_project_fpm:latest"
#    state: absent


- name: Create a data container
  docker_container:
    name: "" 
    image: "localhost:5000/symfony_project_fpm:latest"
    recreate:  
   published_ports:
      - 8080:80
